
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: "🔌  Checkout"
        uses: actions/checkout@v2

      - name: "🔌  Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "🔨 Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: "🔨 Publish aws cdk"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: slashgordon/aws-cdk:$(cat VERSION),slashgordon/aws-cdk:latest
      - name: "🚀 (Github) Release  🚀"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v$(cat VERSION)"
          prerelease: false
          title: "AWS-CDK Docker $(cat VERSION)"
          files: |
            Dockerfile
            VERSION